charts:
  - id: g7EuE
    name: Doses administered
    type: table
  - id: GvEK6
    name: Vaccines administered -- statewide
    type: map
  - id: TIIA3
    name: Vaccines administered -- Chicago
    type: map
  - id: xl8sT
    name: Vaccines administered - Chicago
    type: chart
  - id: qV77i
    name: Inventory by county
    type: table
  - id: Hq3Ai
    name: Vaccine inventory
    type: map
  - id: bvbM8
    name: Data by county
    type: table
  - id: Cf9Pv
    name: Vaccines adminstered -- statewide
    type: chart
