name: run-workflow
on:
  schedule:
    - cron: "40 23 * * *"
  workflow_dispatch:
    inputs:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: "3.7"
      - name: install python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      - name: set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print(dt.datetime.now().date())')" >> $GITHUB_ENV
          echo ""
      - name: run scraper
        run: |
          python src/scrapers/get_cdph_citywide_by_day.py
          python src/scrapers/get_cdph_zip_code_current.py
          python src/scrapers/get_idph_administration_current.py
          python src/scrapers/get_idph_demographics.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Add data for $DATE"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: force datawrapper refresh
        run: |
          python src/update_graphics.py
        env:
          DATAWRAPPER_API_TOKEN: ${{ secrets.DATAWRAPPER_API_TOKEN }}
