name: run-workflow
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
    inputs:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: "3.7"
      - name: install python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      - name: set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print(dt.datetime.now().date())')" >> $GITHUB_ENV
          echo ""
      - name: run scraper
        run: |
          echo scraping CDPH [1/2]
          python src/scrapers/get_cdph_citywide_by_day.py
          echo scraping CDPH [2/2]
          python src/scrapers/get_cdph_zip_code_current.py
          echo scraping IDPH [1/2]
          python src/scrapers/get_idph_administration_current.py
          echo scraping IDPH [2/2]
          python src/scrapers/get_idph_demographics.py
      - name: Prepare Selenium
        uses: nanasess/setup-chromedriver@master
      - name: Launch browser
      - name: Start XVFB
        run: |
           google-chrome --version
           export DISPLAY=:99
           chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
      - name: download-svg
        run: python src/svg_crowbar.py
        env:
          DISPLAY: :99
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Add data for $DATE"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: ${{ env.DATE }}
          files: output/*
      - name: force datawrapper refresh
        run: |
          python src/update_graphics.py
        env:
          DATAWRAPPER_API_TOKEN: ${{ secrets.DATAWRAPPER_API_TOKEN }}
